using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MarkusPalcer.Modularity.CodeGeneration;

[Generator]
public class FactoryGenerator : IIncrementalGenerator
{
    private static readonly Regex Chars = new Regex(@"[^a-zA-Z0-9_\.]", RegexOptions.Compiled);

    private static readonly SymbolDisplayFormat ClassFormat = new(
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypes,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters);

    private static readonly SymbolDisplayFormat ParameterTypeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax,
                transform: (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            // ReSharper disable once ConditionIsAlwaysTrueOrFalseAccordingToNullableAPIContract
            .Where(classDecl => classDecl != null);

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, Generate);
    }

    private static void Generate(SourceProductionContext spc,
        (Compilation Left, ImmutableArray<ClassDeclarationSyntax> Right) tuple)
    {
        var (compilation, classDecls) = tuple;
        var attributeSymbol =
            compilation.GetTypeByMetadataName("MarkusPalcer.Modularity.Attributes.FactoryParameterAttribute");

        var declaredTypes = classDecls.Select(x => compilation.GetSemanticModel(x.SyntaxTree).GetDeclaredSymbol(x))
            .OfType<INamedTypeSymbol>()
            .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        HashSet<int> usedParameterCounts = [];

        foreach (var declaredType in declaredTypes)
        {
            INamedTypeSymbol[] implementedTypes = [declaredType, .. declaredType.AllInterfaces];

            List<Factory> factoryClasses = [];

            foreach (var constructor in declaredType.Constructors)
            {
                Dictionary<string, IParameterSymbol> factoryParameters = [];
                Dictionary<string, IParameterSymbol> resolvedParameters = [];
                foreach (var parameter in constructor.Parameters)
                {
                    var attributes = parameter.GetAttributes();
                    var factoryAttribute =
                        attributes.FirstOrDefault(ad => SymbolEqualityComparer.Default.Equals(
                            ad.AttributeClass, attributeSymbol));
                    if (factoryAttribute is not null)
                    {
                        factoryParameters.Add(parameter.Name, parameter);
                    }
                    else
                    {
                        resolvedParameters.Add(parameter.Name, parameter);
                    }
                }

                if (factoryParameters.Count == 0)
                {
                    continue;
                }

                factoryClasses.AddRange(
                    implementedTypes.Select(type =>
                        GenerateFactory(type, constructor, factoryParameters, resolvedParameters)));
                usedParameterCounts.Add(factoryParameters.Count);
            }

            if (factoryClasses.Count == 0)
            {
                continue;
            }

            var declaredTypeDefinition =
                $"{declaredType.ToDisplayString(ClassFormat)} {string.Join(" ", GetTypeConstraints(declaredType))}";

            var code = $$"""
                         // <auto-generated />

                         #nullable enable

                         using Microsoft.Extensions.DependencyInjection;
                         using System.Diagnostics.CodeAnalysis;
                         using System.CodeDom.Compiler;

                         namespace {{declaredType.ContainingNamespace.ToDisplayString()}};

                         public partial class {{declaredTypeDefinition}} {
                            [ExcludeFromCodeCoverage]
                            [GeneratedCode("MarkusPalcer.Modularity.CodeGeneration", "{{typeof(FactoryGenerator).Assembly.GetName().Version}}")]
                            public partial class Factory(IServiceProvider serviceProvider) : {{string.Join(", ", factoryClasses.Select(x => x.InterfaceName))}} {
                                {{string.Join("\n\n", factoryClasses.Select(x => x.ImplementationCode))}}
                            }
                         }
                         """;

            spc.AddSource($"{Chars.Replace(declaredType.ToDisplayString(), "_")}.Factories.g.cs", code);
        }

        GenerateFactoryInterfaces(usedParameterCounts);
    }

    private static IEnumerable<string> GetTypeConstraints(INamedTypeSymbol classSymbol)
    {
        foreach (var tp in classSymbol.TypeParameters)
        {
            var constraints = new List<string>();

            if (tp.HasReferenceTypeConstraint)
            {
                constraints.Add("class");
            }

            if (tp.HasValueTypeConstraint)
            {
                constraints.Add("struct");
            }

            constraints.AddRange(tp.ConstraintTypes.Select(ct =>
                ct.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));

            if (tp.HasConstructorConstraint)
            {
                constraints.Add("new()");
            }

            if (constraints.Count > 0)
            {
                yield return $"where {tp.Name} : {string.Join(", ", constraints)}";
            }
        }
    }

    private static void GenerateFactoryInterfaces(IEnumerable<int> usedParameterCounts)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using JetBrains.Annotations;");
        sb.AppendLine();
        sb.AppendLine("namespace MarkusPalcer.Modularity");
        sb.AppendLine();
        sb.AppendLine(
            "[UsedImplicitly(ImplicitUseTargetFlags.WithInheritors)] public interface IFactory<TOut> : IFactory { TOut Create(); }");

        foreach (var usedParameterCount in usedParameterCounts.Except([0]))
        {
            var typeParams = string.Join(", ", Enumerable.Range(1, usedParameterCount).Select(x => $"TIn{x}"));
            var parameters = string.Join(", ", Enumerable.Range(1, usedParameterCount).Select(x => $"TIn{x} param{x}"));
            sb.AppendLine(
                $"[UsedImplicitly(ImplicitUseTargetFlags.WithInheritors)] public interface IFactory<{typeParams}, TOut> : IFactory {{ TOut Create({parameters}); }}");
        }
    }

    private class Factory(string interfaceName, string implementationCode)
    {
        public string InterfaceName { get; } = interfaceName;
        public string ImplementationCode { get; } = implementationCode;
    }

    private static Factory GenerateFactory(INamedTypeSymbol resultType,
        IMethodSymbol constructor,
        Dictionary<string, IParameterSymbol> factoryParameters,
        Dictionary<string, IParameterSymbol> resolvedParameters)
    {
        var interfaceName =
            $"MarkusPalcer.Modularity.IFactory<{string.Join(", ", factoryParameters.Values.Select(x => x.Type.ToDisplayString(ParameterTypeFormat)))}, {resultType.ToDisplayString(ParameterTypeFormat)}>";
        var factoryParameterString =
            string.Join(", ",
                factoryParameters.Values.Select(x =>
                    $"{x.Type.ToDisplayString(ParameterTypeFormat)} {x.Name}"));
        var constructorParameterStrings = constructor.Parameters
            .Select(parameter => resolvedParameters.ContainsKey(parameter.Name)
                ? $"{new string(' ', 16)}serviceProvider.GetRequiredService<{parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>()"
                : $"{new string(' ', 16)}{parameter.Name}")
            .ToList();
        var implementationCode = $"""
                                    {resultType.ToDisplayString()} {interfaceName}.Create({factoryParameterString}) 
                                        => new {constructor.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}({string.Join(", ", constructorParameterStrings)});
                                  """;

        return new Factory(interfaceName, implementationCode);
    }
}