using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MarkusPalcer.Modularity.CodeGeneration;

[Generator]
public class FactoryGenerator : IIncrementalGenerator
{
    private static readonly Regex Chars = new Regex(@"[^a-zA-Z0-9_\.]", RegexOptions.Compiled);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
                                       .CreateSyntaxProvider(
                                            predicate: (node, _) => node is ClassDeclarationSyntax,
                                            transform: (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
                                        // ReSharper disable once ConditionIsAlwaysTrueOrFalseAccordingToNullableAPIContract
                                       .Where(classDecl => classDecl != null);

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, Generate);
    }

    private void Generate(SourceProductionContext spc, (Compilation Left, ImmutableArray<ClassDeclarationSyntax> Right) tuple)
    {
        var (compilation, classDecls) = tuple;
        var attributeSymbol =
            compilation.GetTypeByMetadataName("MarkusPalcer.Modularity.Attributes.FactoryParameterAttribute");

        var constructors = classDecls.Select(x => compilation.GetSemanticModel(x.SyntaxTree).GetDeclaredSymbol(x))
                                     .OfType<INamedTypeSymbol>()
                                     .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default)
                                     .SelectMany(x => x.Constructors)
                                     .Where(c => c.Parameters.Any(p => p.GetAttributes()
                                                                        .Any(ad =>
                                                                                 SymbolEqualityComparer.Default.Equals(
                                                                                     ad.AttributeClass,
                                                                                     attributeSymbol))))
                                     .ToList();

        foreach (var constructor in constructors)
        {
            Process(spc, constructor, attributeSymbol);
        }
    }

    private void Process(SourceProductionContext spc, IMethodSymbol constructor, INamedTypeSymbol? attributeSymbol)
    {
        var classSymbol = constructor.ContainingType;

        INamedTypeSymbol[] types = [classSymbol, .. classSymbol.AllInterfaces];

        // Find the parameter annotated with FactoryParameterAttribute
        Dictionary<string, IParameterSymbol> factoryParameters = [];
        Dictionary<string, IParameterSymbol> resolvedParameters = [];
        foreach (var parameter in constructor.Parameters)
        {
            var attributes = parameter.GetAttributes();
            var factoryAttribute =
                attributes.FirstOrDefault(ad => SymbolEqualityComparer.Default.Equals(
                                              ad.AttributeClass, attributeSymbol));
            if (factoryAttribute is not null)
            {
                factoryParameters.Add(parameter.Name, parameter);
            }
            else
            {
                resolvedParameters.Add(parameter.Name, parameter);
            }
        }

        var factories = types.Select(x => GenerateFactoryClass(x, constructor, factoryParameters, resolvedParameters))
                             .ToArray();

        var code = $$"""
                     // <auto-generated />
                     using Microsoft.Extensions.DependencyInjection;
                     using System.Diagnostics.CodeAnalysis;

                     namespace {{classSymbol.ContainingNamespace.ToDisplayString()}};

                     public partial class {{classSymbol.Name}} {
                     {{string.Join("\n", factories)}}
                     }
                     """;

        var constructorName = $"{classSymbol.ToDisplayString()}";
        var fileName = $"{Chars.Replace(constructorName, "_")}.Factories.g.cs";

        spc.AddSource(fileName, code);
    }

    private string GenerateFactoryClass(INamedTypeSymbol result,
                                        IMethodSymbol constructor,
                                        Dictionary<string, IParameterSymbol> factoryParameters,
                                        Dictionary<string, IParameterSymbol> resolvedParameters)
    {

        var sb = new StringBuilder();

        sb.AppendLine($"{new string(' ', 4)}[ExcludeFromCodeCoverage]");
        sb.Append($"{new string(' ', 4)}public class {result.Name}Factory(IServiceProvider serviceProvider) : MarkusPalcer.Modularity.IFactory<");
        sb.Append(string.Join(", ", factoryParameters.Values.Select(x => x.Type.ToDisplayString())));
        sb.Append(", ");
        sb.Append(result.ToDisplayString());
        sb.AppendLine("> {");

        sb.Append($"{new string(' ', 8)}public {result.ToDisplayString()} Create(");
        sb.Append(string.Join(", ", factoryParameters.Values.Select(x => $"{x.Type.ToDisplayString()} {x.Name}")));
        sb.AppendLine(") {");

        sb.AppendLine($"{new string(' ', 12)}return new {constructor.ContainingType.ToDisplayString()}(");

        var parameters = new List<string>();
        foreach (var parameter in constructor.Parameters)
        {
            if (resolvedParameters.ContainsKey(parameter.Name))
            {
                parameters.Add($"{new string(' ', 16)}serviceProvider.GetRequiredService<{parameter.Type.ToDisplayString()}>()");
            }
            else
            {
                parameters.Add($"{new string(' ', 16)}{parameter.Name}");
            }
        }
        sb.AppendLine(string.Join($",\n", parameters));

        sb.AppendLine($"{new string(' ', 12)});");
        sb.AppendLine($"{new string(' ', 8)}}}");
        sb.AppendLine($"{new string(' ', 4)}}}");

        return sb.ToString();
    }
}
